version: '3.4'
networks:
  backend:
    driver: bridge
volumes:
  mysql-data:
    driver: local
services:
  bbdd:
    container_name: mysqlContainer
    image: mysql:8.0  
    restart: always
    ports:
      - "3306:3306"  
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "FMfcgzQZTCqZPnrwkWsNZDNDsqtphSfr"
      MYSQL_DATABASE: "bbddAcademIQ"
  api:
    container_name: apiContainer
    image: reto2_api:1.0  
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5687:80"
    networks:
      - backend
    depends_on:
      - bbdd
    environment:
      bbddAcademIQ: "server=mysqlContainer;port=3306;Database=bbddAcademIQ;Uid=root;Pwd=FMfcgzQZTCqZPnrwkWsNZDNDsqtphSfr;"