version: '3.8'

networks:
  backend:

volumes:
  sqlserver-data:
    driver: local

services:
  bbdd:
    container_name: dbContainer
    image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'yourStrong.Password'
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - sqlserver-data:/var/opt/mssql

  api:
    container_name: apiContainer
    image: reto2_api:1.0
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    networks:
      - backend
    depends_on:
      - bbdd

  web:
    container_name: webContainer
    image: web:1.0
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.web # Asegúrate de tener este Dockerfile para el frontend
    ports:
      - "9000:8080"
    networks:
      - backend
    depends_on:
      - api
